In [233]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [234]:
links = pd.read_csv('links.csv')
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [235]:
movies = pd.read_csv('movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [236]:
ratings = pd.read_csv('ratings.csv')
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [237]:
tags = pd.read_csv('tags.csv')
tags.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [238]:
merged_df = pd.merge(links, movies, on='movieId', how='left')
merged_df.head(5)

,movieId,imdbId,tmdbId,title,genres
0,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,113497,8844.0,Jumanji (1995),Adventure|Children|Fantasy
2,3,113228,15602.0,Grumpier Old Men (1995),Comedy|Romance
3,4,114885,31357.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,113041,11862.0,Father of the Bride Part II (1995),Comedy

In [239]:
merged_df_m = pd.merge(merged_df, ratings, on='movieId', how='left')
merged_df_m.head(10)

,movieId,imdbId,tmdbId,title,genres,userId,rating,timestamp
0,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08
1,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08
2,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09
3,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09
4,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09
5,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18.0,3.5,1.455210e+09
6,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,4.0,9.657056e+08
7,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21.0,3.5,1.407619e+09
8,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27.0,3.0,9.626853e+08
9,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31.0,5.0,8.504666e+08

In [240]:
merged_df_m.shape

(100854, 8)

In [241]:
merged_df_all = pd.merge(merged_df_m, tags, on=['movieId','userId'], how='left')
merged_df_all.head()

,movieId,imdbId,tmdbId,title,genres,userId,rating,timestamp_x,tag,timestamp_y
0,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08,NaN,NaN
1,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08,NaN,NaN
2,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09,NaN,NaN
3,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09,NaN,NaN
4,1,114709,862.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09,NaN,NaN

In [249]:
merged_df_all.columns

Index(['movieId', 'imdbId', 'tmdbId', 'title', 'genres', 'userId', 'rating',
       'timestamp_x', 'tag', 'timestamp_y'],
      dtype='object')

In [242]:
print(f'links shape: {links.shape}')
print(f'movies shape: {movies.shape}')
print(f'ratings shape: {ratings.shape}')
print(f'tags shape: {tags.shape}')
print(f'merged data shape: {merged_df_all.shape}')

links shape: (9742, 3)
movies shape: (9742, 3)
ratings shape: (100836, 4)
tags shape: (3683, 4)
merged data shape: (102695, 10)

In [243]:
merged_df_all.isna().count()

movieId        102695
imdbId         102695
tmdbId         102695
title          102695
genres         102695
userId         102695
rating         102695
timestamp_x    102695
tag            102695
timestamp_y    102695
dtype: int64

In [244]:
merged_df_all.columns

Index(['movieId', 'imdbId', 'tmdbId', 'title', 'genres', 'userId', 'rating',
       'timestamp_x', 'tag', 'timestamp_y'],
      dtype='object')

In [245]:
merged_df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102695 entries, 0 to 102694
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   movieId      102695 non-null  int64
 1   imdbId       102695 non-null  int64
 2   tmdbId       102682 non-null  float64
 3   title        102695 non-null  object
 4   genres       102695 non-null  object
 5   userId       102677 non-null  float64
 6   rating       102677 non-null  float64
 7   timestamp_x  102677 non-null  float64
 8   tag          3476 non-null    object
 9   timestamp_y  3476 non-null    float64
dtypes: float64(5), int64(2), object(3)
memory usage: 7.8+ MB

In [246]:
merged_df_all.describe()

,movieId,imdbId,tmdbId,userId,rating,timestamp_x,timestamp_y
count,102695.000000,1.026950e+05,102682.000000,102677.000000,102677.000000,1.026770e+05,3.476000e+03
mean,19742.419125,3.564670e+05,20477.542257,327.761933,3.514813,1.209495e+09,1.323525e+09
std,35882.264342,6.295366e+05,54093.268790,183.211289,1.043133,2.170117e+08,1.731554e+08
min,1.000000,4.170000e+02,2.000000,1.000000,0.500000,8.281246e+08,1.137179e+09
25%,1199.000000,9.970300e+04,710.000000,177.000000,3.000000,1.019138e+09,1.138032e+09
50%,3005.000000,1.188420e+05,6951.000000,328.000000,3.500000,1.186590e+09,1.279956e+09
75%,8366.000000,3.172480e+05,11673.750000,477.000000,4.000000,1.439916e+09,1.498457e+09
max,193609.000000,8.391976e+06,525662.000000,610.000000,5.000000,1.537799e+09,1.537099e+09

In [247]:
merged_df_all['genres'].nunique()

951

In [248]:
merged_df_all['title'].nunique()

9737